### ISSUE TITLE
Backport BugFixes to 1.18.2/1.19.* Fabric?

### ISSUE THREAD

**Issue by jFIreW01F** [PrimordialMoros/Bending#58]
### Is your feature request related to a problem?

Not Necessarily.

### Describe the solution you are proposing.

Um... Self-Explanatory Title.

Please Backport Bugfixes to 1.18.* or 1.19.*

But if You Don't Wan't To Then Obviously Don't.  But Thank You For Reading This Atleast  :)

### Describe alternatives you've considered.

There Aren't Any other Mods That Add Bending, That are Anywhere Close To Being this Good.  Unfortunately

**Comment by PrimordialMoros** [comment]
The primary focus is on the latest minecraft release in order to make full use of modern features and mechanics (eg display entities are needed for various abilities).

Keep in mind, this project also supports other platforms too and maintaining older versions would require significant effort.

Personally I have no interest in those versions but PRs are welcome if someone else chooses to contribute!
