### ISSUE TITLE
Fall Damage/EnchantedArmors

### ISSUE THREAD

**Issue by aqua-air** [PrimordialMoros/Bending#66]
### Bending Version

3.8.0

### Platform Details

Purpur 1.20.6 - v2233

### Mod/Plugin List

![Screenshot 2024-06-22 111642](https://github.com/PrimordialMoros/Bending/assets/56618632/5eb4f5e6-260b-4435-8331-810b1d1c1106)

### Bug Description

My only issues after playing with this for about a month: 

1-  Wearing enchanted armors (iron/dia/etc) makes a lot of bending stop working.  I know for sure, torrent, watermanip, earthblast...
2- Fall damage doesn't operate right with Earth Bending, they take fall damage on grass and stone, etc.. even after choosing and 
relogging earth. 
3-  EarthGlove spawns items as reported in discord 

Main issue is #2, earth sucks when you die so easily from catapult.  Excellent Plugin, I hope to see more of it! 

### Reproduction Steps

use catapult, land on stone, die

### Expected Behavior

Don't die

**Comment by aqua-air** [comment]
*** I did test removing crazy enchantments, essentialsx, gsit, factions, playerpoints, and the issue with enchanted armor remains.

**Comment by PrimordialMoros** [comment]
Do not combine multiple bug reports in a single issue.

1. Is unrelated to bending and caused by one of your other plugins
2. See above. If it continues to happen in a clean environment without other plugins, I'll need more details about it as I've been unable to reproduce it.
3. Already reported and fixed (#64).

Reopen the bug report for fall damage if needed.
